version: "3.3"
services:
  rest:
    build:
      dockerfile: docker/rest/Dockerfile
      context: .
    ports:
      - "8080:80"
    tty: true

  test:
    build:
      dockerfile: docker/test/Dockerfile
      context: .
    volumes:
      - .:/opt