// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/app/grpc/proto/common.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Date struct {
	Utc                  int64    `protobuf:"varint,1,opt,name=utc,proto3" json:"utc,omitempty"`
	Rfc                  string   `protobuf:"bytes,2,opt,name=rfc,proto3" json:"rfc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_90af7cc4894ae49d, []int{0}
}

func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (m *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(m, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

func (m *Date) GetUtc() int64 {
	if m != nil {
		return m.Utc
	}
	return 0
}

func (m *Date) GetRfc() string {
	if m != nil {
		return m.Rfc
	}
	return ""
}

func init() {
	proto.RegisterType((*Date)(nil), "proto.Date")
}

func init() {
	proto.RegisterFile("internal/app/grpc/proto/common.proto", fileDescriptor_90af7cc4894ae49d)
}

var fileDescriptor_90af7cc4894ae49d = []byte{
	// 105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xc9, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x4f, 0x2c, 0x28, 0xd0, 0x4f, 0x2f, 0x2a, 0x48, 0xd6, 0x2f, 0x28,
	0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0xd3, 0x03, 0x73, 0x84, 0x58, 0xc1,
	0x94, 0x92, 0x16, 0x17, 0x8b, 0x4b, 0x62, 0x49, 0xaa, 0x90, 0x00, 0x17, 0x73, 0x69, 0x49, 0xb2,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x88, 0x09, 0x12, 0x29, 0x4a, 0x4b, 0x96, 0x60, 0x52,
	0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x93, 0xd8, 0xc0, 0x5a, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xd0, 0x07, 0xe6, 0xb1, 0x61, 0x00, 0x00, 0x00,
}
