// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/app/grpc/proto/fixture.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Fixture struct {
	Id                   int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Competition          *Competition `protobuf:"bytes,2,opt,name=competition,proto3" json:"competition,omitempty"`
	Season               *Season      `protobuf:"bytes,3,opt,name=season,proto3" json:"season,omitempty"`
	HomeTeam             *Team        `protobuf:"bytes,4,opt,name=home_team,json=homeTeam,proto3" json:"home_team,omitempty"`
	AwayTeam             *Team        `protobuf:"bytes,5,opt,name=away_team,json=awayTeam,proto3" json:"away_team,omitempty"`
	Round                *Round       `protobuf:"bytes,6,opt,name=round,proto3" json:"round,omitempty"`
	Venue                *Venue       `protobuf:"bytes,7,opt,name=venue,proto3" json:"venue,omitempty"`
	DateTime             *Date        `protobuf:"bytes,8,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Fixture) Reset()         { *m = Fixture{} }
func (m *Fixture) String() string { return proto.CompactTextString(m) }
func (*Fixture) ProtoMessage()    {}
func (*Fixture) Descriptor() ([]byte, []int) {
	return fileDescriptor_4644bcaf0dffb40d, []int{0}
}

func (m *Fixture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fixture.Unmarshal(m, b)
}
func (m *Fixture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fixture.Marshal(b, m, deterministic)
}
func (m *Fixture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fixture.Merge(m, src)
}
func (m *Fixture) XXX_Size() int {
	return xxx_messageInfo_Fixture.Size(m)
}
func (m *Fixture) XXX_DiscardUnknown() {
	xxx_messageInfo_Fixture.DiscardUnknown(m)
}

var xxx_messageInfo_Fixture proto.InternalMessageInfo

func (m *Fixture) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Fixture) GetCompetition() *Competition {
	if m != nil {
		return m.Competition
	}
	return nil
}

func (m *Fixture) GetSeason() *Season {
	if m != nil {
		return m.Season
	}
	return nil
}

func (m *Fixture) GetHomeTeam() *Team {
	if m != nil {
		return m.HomeTeam
	}
	return nil
}

func (m *Fixture) GetAwayTeam() *Team {
	if m != nil {
		return m.AwayTeam
	}
	return nil
}

func (m *Fixture) GetRound() *Round {
	if m != nil {
		return m.Round
	}
	return nil
}

func (m *Fixture) GetVenue() *Venue {
	if m != nil {
		return m.Venue
	}
	return nil
}

func (m *Fixture) GetDateTime() *Date {
	if m != nil {
		return m.DateTime
	}
	return nil
}

func init() {
	proto.RegisterType((*Fixture)(nil), "proto.Fixture")
}

func init() {
	proto.RegisterFile("internal/app/grpc/proto/fixture.proto", fileDescriptor_4644bcaf0dffb40d)
}

var fileDescriptor_4644bcaf0dffb40d = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x6d, 0x6a, 0x7f, 0x9c, 0x68, 0x17, 0x03, 0xc2, 0xd0, 0x55, 0x89, 0x56, 0xe2, 0x26,
	0x81, 0x2a, 0x3e, 0x80, 0x16, 0xd1, 0xed, 0xb4, 0xb8, 0x2d, 0x63, 0x72, 0xd5, 0x01, 0x27, 0x13,
	0x27, 0x93, 0x6a, 0xdf, 0xcd, 0x87, 0x93, 0xf9, 0xa1, 0x36, 0x60, 0xec, 0x2a, 0xc9, 0x39, 0xdf,
	0xe5, 0xdc, 0x7b, 0x08, 0x9a, 0xf2, 0x42, 0x83, 0x2a, 0xd8, 0x7b, 0xca, 0xca, 0x32, 0x7d, 0x55,
	0x65, 0x96, 0x96, 0x4a, 0x6a, 0x99, 0xbe, 0xf0, 0x2f, 0x5d, 0x2b, 0x48, 0xec, 0x17, 0xee, 0xd9,
	0xc7, 0xf8, 0xbc, 0x8d, 0xce, 0xa4, 0x10, 0xb2, 0x70, 0xf0, 0xf8, 0xf2, 0x1f, 0xaa, 0x04, 0xcd,
	0x35, 0xdf, 0xa2, 0x17, 0x6d, 0xa8, 0x82, 0x8f, 0x1a, 0x2a, 0x5d, 0x79, 0xee, 0xac, 0x95, 0x93,
	0x75, 0x91, 0x27, 0x7b, 0xb6, 0xab, 0x80, 0x55, 0xdb, 0xc8, 0xa8, 0x8d, 0xd2, 0xc0, 0xc4, 0xbe,
	0xb8, 0x35, 0x14, 0xb5, 0xef, 0x24, 0xfa, 0x0e, 0xd0, 0xe0, 0xde, 0xb5, 0x84, 0x47, 0x28, 0xe0,
	0x39, 0xe9, 0x4c, 0x3a, 0x71, 0x97, 0x06, 0x3c, 0xc7, 0xd7, 0x28, 0xdc, 0x39, 0x96, 0x04, 0x93,
	0x4e, 0x1c, 0xce, 0xb0, 0x1b, 0x4c, 0xee, 0x7e, 0x1d, 0xba, 0x8b, 0xe1, 0x29, 0xea, 0xbb, 0x55,
	0x49, 0xd7, 0x0e, 0x9c, 0xf8, 0x81, 0x85, 0x15, 0xa9, 0x37, 0x71, 0x8c, 0x8e, 0xde, 0xa4, 0x80,
	0x95, 0x59, 0x98, 0x1c, 0x5a, 0x32, 0xf4, 0xe4, 0x12, 0x98, 0xa0, 0x43, 0xe3, 0x9a, 0x37, 0x43,
	0xb2, 0x4f, 0xb6, 0x71, 0x64, 0xef, 0x0f, 0xd2, 0xb8, 0x96, 0x8c, 0x50, 0xcf, 0x56, 0x49, 0xfa,
	0x96, 0x3a, 0xf6, 0x14, 0x35, 0x1a, 0x75, 0x96, 0x61, 0xec, 0xfd, 0x64, 0xd0, 0x60, 0x9e, 0x8c,
	0x46, 0x9d, 0x65, 0x12, 0x73, 0xa6, 0x61, 0xa5, 0xb9, 0x00, 0x32, 0x6c, 0x24, 0xce, 0x99, 0x06,
	0x3a, 0x34, 0xee, 0x92, 0x0b, 0x98, 0x3d, 0xa0, 0x91, 0x6f, 0x6f, 0x01, 0x6a, 0xcd, 0x33, 0xc0,
	0x37, 0x28, 0xf4, 0xca, 0xed, 0xe6, 0x71, 0x8e, 0x4f, 0xfd, 0x9c, 0xd7, 0xa8, 0xfb, 0x23, 0xc6,
	0xa3, 0xa6, 0x1c, 0x1d, 0x3c, 0xf7, 0xad, 0x70, 0xf5, 0x13, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xfc,
	0x70, 0xe8, 0xcc, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FixtureServiceClient is the client API for FixtureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FixtureServiceClient interface {
	FixtureByID(ctx context.Context, in *FixtureRequest, opts ...grpc.CallOption) (*Fixture, error)
}

type fixtureServiceClient struct {
	cc *grpc.ClientConn
}

func NewFixtureServiceClient(cc *grpc.ClientConn) FixtureServiceClient {
	return &fixtureServiceClient{cc}
}

func (c *fixtureServiceClient) FixtureByID(ctx context.Context, in *FixtureRequest, opts ...grpc.CallOption) (*Fixture, error) {
	out := new(Fixture)
	err := c.cc.Invoke(ctx, "/proto.FixtureService/FixtureByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FixtureServiceServer is the server API for FixtureService service.
type FixtureServiceServer interface {
	FixtureByID(context.Context, *FixtureRequest) (*Fixture, error)
}

// UnimplementedFixtureServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFixtureServiceServer struct {
}

func (*UnimplementedFixtureServiceServer) FixtureByID(ctx context.Context, req *FixtureRequest) (*Fixture, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FixtureByID not implemented")
}

func RegisterFixtureServiceServer(s *grpc.Server, srv FixtureServiceServer) {
	s.RegisterService(&_FixtureService_serviceDesc, srv)
}

func _FixtureService_FixtureByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FixtureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FixtureServiceServer).FixtureByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FixtureService/FixtureByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FixtureServiceServer).FixtureByID(ctx, req.(*FixtureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FixtureService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FixtureService",
	HandlerType: (*FixtureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FixtureByID",
			Handler:    _FixtureService_FixtureByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/app/grpc/proto/fixture.proto",
}
