// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/app/grpc/proto/odds_compiler.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventRequest struct {
	EventId              uint64   `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Market               string   `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventRequest) Reset()         { *m = EventRequest{} }
func (m *EventRequest) String() string { return proto.CompactTextString(m) }
func (*EventRequest) ProtoMessage()    {}
func (*EventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c89f6ecd9bce4745, []int{0}
}

func (m *EventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRequest.Unmarshal(m, b)
}
func (m *EventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRequest.Marshal(b, m, deterministic)
}
func (m *EventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRequest.Merge(m, src)
}
func (m *EventRequest) XXX_Size() int {
	return xxx_messageInfo_EventRequest.Size(m)
}
func (m *EventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventRequest proto.InternalMessageInfo

func (m *EventRequest) GetEventId() uint64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *EventRequest) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

type EventMarket struct {
	EventId              uint64   `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Market               string   `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Odds                 []*Odds  `protobuf:"bytes,3,rep,name=odds,proto3" json:"odds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventMarket) Reset()         { *m = EventMarket{} }
func (m *EventMarket) String() string { return proto.CompactTextString(m) }
func (*EventMarket) ProtoMessage()    {}
func (*EventMarket) Descriptor() ([]byte, []int) {
	return fileDescriptor_c89f6ecd9bce4745, []int{1}
}

func (m *EventMarket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventMarket.Unmarshal(m, b)
}
func (m *EventMarket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventMarket.Marshal(b, m, deterministic)
}
func (m *EventMarket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMarket.Merge(m, src)
}
func (m *EventMarket) XXX_Size() int {
	return xxx_messageInfo_EventMarket.Size(m)
}
func (m *EventMarket) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMarket.DiscardUnknown(m)
}

var xxx_messageInfo_EventMarket proto.InternalMessageInfo

func (m *EventMarket) GetEventId() uint64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *EventMarket) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *EventMarket) GetOdds() []*Odds {
	if m != nil {
		return m.Odds
	}
	return nil
}

type Odds struct {
	Price                float32  `protobuf:"fixed32,1,opt,name=price,proto3" json:"price,omitempty"`
	Selection            string   `protobuf:"bytes,2,opt,name=selection,proto3" json:"selection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Odds) Reset()         { *m = Odds{} }
func (m *Odds) String() string { return proto.CompactTextString(m) }
func (*Odds) ProtoMessage()    {}
func (*Odds) Descriptor() ([]byte, []int) {
	return fileDescriptor_c89f6ecd9bce4745, []int{2}
}

func (m *Odds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Odds.Unmarshal(m, b)
}
func (m *Odds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Odds.Marshal(b, m, deterministic)
}
func (m *Odds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Odds.Merge(m, src)
}
func (m *Odds) XXX_Size() int {
	return xxx_messageInfo_Odds.Size(m)
}
func (m *Odds) XXX_DiscardUnknown() {
	xxx_messageInfo_Odds.DiscardUnknown(m)
}

var xxx_messageInfo_Odds proto.InternalMessageInfo

func (m *Odds) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Odds) GetSelection() string {
	if m != nil {
		return m.Selection
	}
	return ""
}

func init() {
	proto.RegisterType((*EventRequest)(nil), "proto.EventRequest")
	proto.RegisterType((*EventMarket)(nil), "proto.EventMarket")
	proto.RegisterType((*Odds)(nil), "proto.Odds")
}

func init() {
	proto.RegisterFile("internal/app/grpc/proto/odds_compiler.proto", fileDescriptor_c89f6ecd9bce4745)
}

var fileDescriptor_c89f6ecd9bce4745 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xed, 0xd6, 0x4d, 0xf7, 0x2a, 0x1e, 0x32, 0x91, 0x2a, 0x82, 0xa5, 0xa7, 0x82, 0xb0,
	0xc2, 0xbc, 0xe9, 0x49, 0x44, 0xc4, 0x83, 0x08, 0xf1, 0x03, 0x8c, 0x9a, 0x3c, 0x24, 0xd8, 0x25,
	0x31, 0x89, 0xfd, 0xfc, 0x92, 0xd7, 0x80, 0x3d, 0xef, 0x14, 0x7e, 0xff, 0xe4, 0xfd, 0xf2, 0x4f,
	0xe0, 0x56, 0xe9, 0x80, 0x4e, 0x77, 0x7d, 0xdb, 0x59, 0xdb, 0x7e, 0x39, 0x2b, 0x5a, 0xeb, 0x4c,
	0x30, 0xad, 0x91, 0xd2, 0xef, 0x84, 0xd9, 0x5b, 0xd5, 0xa3, 0xdb, 0x50, 0xc6, 0x16, 0xb4, 0xd4,
	0x8f, 0x70, 0xfa, 0x3c, 0xa0, 0x0e, 0x1c, 0x7f, 0x7e, 0xd1, 0x07, 0x76, 0x09, 0x27, 0x18, 0x79,
	0xa7, 0x64, 0x99, 0x55, 0x59, 0x93, 0xf3, 0x63, 0xe2, 0x57, 0xc9, 0x2e, 0x60, 0xb9, 0xef, 0xdc,
	0x37, 0x86, 0x72, 0x56, 0x65, 0xcd, 0x8a, 0x27, 0xaa, 0x3b, 0x28, 0x48, 0xf1, 0x46, 0x78, 0x80,
	0x81, 0xdd, 0x40, 0x1e, 0x2b, 0x96, 0xf3, 0x6a, 0xde, 0x14, 0xdb, 0x62, 0x6c, 0xb8, 0x79, 0x97,
	0xd2, 0x73, 0xda, 0xa8, 0xef, 0x21, 0x8f, 0xc4, 0xce, 0x61, 0x61, 0x9d, 0x12, 0x48, 0xe2, 0x19,
	0x1f, 0x81, 0x5d, 0xc3, 0xca, 0x63, 0x8f, 0x22, 0x28, 0xa3, 0x93, 0xf9, 0x3f, 0xd8, 0x72, 0x58,
	0xc7, 0xd9, 0xa7, 0xf4, 0xfc, 0x0f, 0x74, 0x43, 0x1c, 0x7a, 0x80, 0xb3, 0x17, 0x0c, 0xd3, 0xe2,
	0xeb, 0x74, 0xef, 0xf4, 0x3f, 0xae, 0xd8, 0x34, 0x1c, 0x0f, 0xd6, 0x47, 0x9f, 0x4b, 0x0a, 0xef,
	0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xef, 0xbd, 0xd7, 0x01, 0x72, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OddsCompilerServiceClient is the client API for OddsCompilerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OddsCompilerServiceClient interface {
	// Returns market for a given event
	GetEventMarket(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventMarket, error)
}

type oddsCompilerServiceClient struct {
	cc *grpc.ClientConn
}

func NewOddsCompilerServiceClient(cc *grpc.ClientConn) OddsCompilerServiceClient {
	return &oddsCompilerServiceClient{cc}
}

func (c *oddsCompilerServiceClient) GetEventMarket(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventMarket, error) {
	out := new(EventMarket)
	err := c.cc.Invoke(ctx, "/proto.OddsCompilerService/GetEventMarket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OddsCompilerServiceServer is the server API for OddsCompilerService service.
type OddsCompilerServiceServer interface {
	// Returns market for a given event
	GetEventMarket(context.Context, *EventRequest) (*EventMarket, error)
}

// UnimplementedOddsCompilerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOddsCompilerServiceServer struct {
}

func (*UnimplementedOddsCompilerServiceServer) GetEventMarket(ctx context.Context, req *EventRequest) (*EventMarket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventMarket not implemented")
}

func RegisterOddsCompilerServiceServer(s *grpc.Server, srv OddsCompilerServiceServer) {
	s.RegisterService(&_OddsCompilerService_serviceDesc, srv)
}

func _OddsCompilerService_GetEventMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OddsCompilerServiceServer).GetEventMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OddsCompilerService/GetEventMarket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OddsCompilerServiceServer).GetEventMarket(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OddsCompilerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.OddsCompilerService",
	HandlerType: (*OddsCompilerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEventMarket",
			Handler:    _OddsCompilerService_GetEventMarket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/app/grpc/proto/odds_compiler.proto",
}
