version: 2
jobs:
  build:
    working_directory: ~/go/src/github.com/statistico/statistico-bet-finder
    machine: true
    environment:
      GOPATH: /home/circleci/go

    steps:
      - checkout

      - run:
          name: Build Release Image
          command: |
            docker-compose -f docker-compose.build.yml up -d --build

      - run:
          name: Test Release Image
          command: |
            docker-compose -f docker-compose.build.yml run test gotestsum -f short-verbose

      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh-keyscan $PRODUCTION_SERVER >> ~/.ssh/known_hosts
              chmod +x ./.circleci/deploy/docker-push.sh
              ./.circleci/deploy/docker-push.sh
              chmod +x ./.circleci/deploy/docker-deploy.sh
              ./.circleci/deploy/docker-deploy.sh
            fi