#!/bin/bash

set -e

RELEASE=$CIRCLE_SHA1
BETFAIR_USERNAME=${BETFAIR_USERNAME}
BETFAIR_PASSWORD=${BETFAIR_PASSWORD}
BETFAIR_KEY=${BETFAIR_KEY}
DATA_SERVICE_HOST=${DATA_SERVICE_HOST}
DATA_SERVICE_PORT=${DATA_SERVICE_PORT}
ODDS_COMPILER_SERVICE_HOST=${ODDS_COMPILER_SERVICE_HOST}
ODDS_COMPILER_SERVICE_PORT=${ODDS_COMPILER_SERVICE_PORT}

scp -r -o StrictHostKeyChecking=no docker-compose.production.yml root@${PRODUCTION_SERVER}:~

ssh -t root@${PRODUCTION_SERVER} 'export RELEASE='"'$RELEASE'"' export BETFAIR_USERNAME='"'$BETFAIR_USERNAME'"' export BETFAIR_PASSWORD='"'$BETFAIR_PASSWORD'"' export BETFAIR_KEY='"'$BETFAIR_KEY'"' export DATA_SERVICE_HOST='"'$DATA_SERVICE_HOST'"' export DATA_SERVICE_PORT='"'$DATA_SERVICE_PORT'"' export ODDS_COMPILER_SERVICE_HOST='"'$ODDS_COMPILER_SERVICE_HOST'"' export ODDS_COMPILER_SERVICE_PORT='"'$ODDS_COMPILER_SERVICE_PORT'"'\

docker-compose -f ./docker-compose.production.yml pull rest && \

docker-compose -f ./docker-compose.production.yml up -d'
